### ISSUE TITLE
Allow dev.azure url for vsts repos.

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/skyux-lib-stache#55]
### Expected behavior
Adding a url to the VSTS repo for `dev.azure` instead of `blackbaud.visualstudio` should still use the `vsts` properties in the edit button

### Actual behavior
the edit button looks specifically for the `visualstudio` keyword in order to use the VSTS url builder options.

### Fix:
update the edit button logic to search for the `dev.azure` or `visualstuidio` in the url to use the appropriate repo location.

**Comment by Blackbaud-LindseyRix** [comment]
This has been resolved.
