### ISSUE TITLE
Action buttons don't always fill available vertical space in row

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-lib-stache#82]
### Expected behavior
Action buttons should always fill entire vertical and horizontal space of the row.

### Actual behavior
When action buttons in a row contain long descriptions, it will case the row to vertically expand. The other action buttons in the same row do not expand to fill that new space, causing each button to have differing heights.

<img width="1030" alt="Screen Shot 2020-07-10 at 11 49 40 AM" src="https://user-images.githubusercontent.com/18354182/87173271-7ebd1480-c2a3-11ea-8aaa-ba861ea67b95.png">

This was introduced in v3.4.0

**Comment by Blackbaud-LindseyRix** [comment]
We don't plan to continue these action buttons for much longer, we plan to switch to the sky action buttons. We're just waiting on the search feature for the sky action buttons. So I'm going to close as we won't address this work.
